# Generated by Django 5.2.3 on 2025-07-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('autor', models.CharField(max_length=70)),
                ('descricao', models.TextField(blank=True)),
                ('capa_url', models.URLField(blank=True)),
                ('data_publicacao', models.CharField(blank=True, max_length=50)),
                ('lido', models.BooleanField(default=False)),
            ],
        ),
    ]
