# Generated by Django 5.2.3 on 2025-07-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
