# Generated by Django 5.2.3 on 2025-07-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
